# Generated by Django 4.2.11 on 2024-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestquotecontact_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotecontact',
            name='occupation',
            field=models.CharField(help_text='What you do, i.e., student, software developer, etc.', max_length=100),
        ),
    ]
