# Generated by Django 4.2.11 on 2024-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requestquotecontact_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquotecontact',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
